FROM node:20-alpine

WORKDIR /app

COPY package*.json ./
RUN npm install

COPY src ./src
COPY prisma ./prisma

RUN npx prisma generate

EXPOSE 3001

CMD ["npx", "nodemon", "--watch", "src", "--exec", "node", "src/index.js"]
